name: Release Nova to npm

on:
  push:
    branches: [ develop ]
  workflow_dispatch:
    inputs:
      version:
        description: The version to bump
        required: true
        default: 'patch'
        type: choice
        options:
          - "patch"
          - "minor"
          - "major"
          - "prepatch"
          - "preminor"
          - "premajor"
          - "prerelease"

env:
  MAINTAINER_MAIL: "jozefmajzel1@gmail"
  MAINTAINER_NAME: "Jozef Majzel"

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    name: "Release Nova @next"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Build
        run: yarn build

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Setup git user and npm
        run: |
          git config --global user.name "$MAINTAINER_NAME"
          git config --global user.email "$MAINTAINER_MAIL"
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      - name: Install dependencies
        run: npm ci

      - name: Bump version @next
        if: ${{ github.event_name == 'push' || steps.extract_branch.outputs.branch == 'develop' }}
        run: npm run release:next
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_USER: "$MAINTAINER_MAIL:${{ secrets.GH_TOKEN }}"
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Bump version @${{ github.event.inputs.version }}
        if: ${{ github.event_name == 'workflow_dispatch' && steps.extract_branch.outputs.branch != 'develop' }}
        run: npm run release -- ${{ github.event.inputs.version }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_USER: "$MAINTAINER_MAIL:${{ secrets.GH_TOKEN }}"
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Publish packages
        run: npm run publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_USER: "$MAINTAINER_MAIL:${{ secrets.GH_TOKEN }}"
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
